### PR TITLE
fix: The issue of ambiguous language reply solved

### PR DESCRIPTION
**Pull request by Harmanpreet-Microsoft**
## Purpose
To resolve the bug for language ambiguity when said Hi to the bot the reply is in spanish

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

## What to Check
Verify that the following are valid
When bot is communicated in particular language it replies in the language itself 

image

### CODE REVIEW

**Comment by adamdougal** [comment]
@Harmanpreet-Microsoft please see https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/1149#issuecomment-2235692030. It needs addressing before this PR can be approved and merged. Thanks

**Comment by Harmanpreet-Microsoft** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by Harmanpreet-Microsoft** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by Harmanpreet-Microsoft** [comment]
Hi @adamdougal 
I have completed the needful task

**Review by adamdougal — APPROVED** [review]

**Pull request merged**
