### PR TITLE
feat: Use openai client for Azure BYOD

### LINKED ISSUE #602: Use openai package for `/api/conversation/azure_byod` endpoint when using data
# Motivation

For requests to `/api/custom/azure_byod`, we currently use the `requests` package when using data, yet we use the `openai` package when not using data, leading to code duplication. We can use the `openai` package for both scenarios, using the `extra_body` property when using data, as shown in the [docs](https://learn.microsoft.com/en-us/azure/ai-services/openai/references/on-your-data?tabs=python#examples).

# Requirements

A list of requirements to consider this feature delivered
- Remove `requests` call to Azure OpenAI and replace with `openai` package.

# Tasks

_To be filled in by the engineer picking up the issue_

### PR DESCRIPTION
**Pull request by cecheta**
Closes #602, required for #295

## Purpose

* This PR updates the byod endpoint to use the `openai` package when calling Azure OpenAI, rather than making a HTTP request with `requests`. This matches official documentation
* Adds (unrelated) tests to not drop coverage

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
* Deploy code
* Change frontend code to use BYOD endpoint
* Chat

## What to Check
* Response received
  * With/without streaming
  * RBAC/keys

### CODE REVIEW

**Comment by ross-p-smith** [comment]
Based on your description, I agree - why would we just front GPT - this is meant to be about Search. @ruoccofabrizio and @gmndrg - can you confirm you are Ok with this principle please?

**Comment by gmndrg** [comment]
@ross-p-smith this is an AI Search accelerator, correct, so it is to use this specific product and how to. Thank you!

**Comment by ruoccofabrizio** [comment]
This is part of the effort to keep a single front end for multiple backend:
- Standard GPT
- Chat with your own data
- Custom Backend
I won't remove it as it's used by customers and removing it doesn't add any value.

**Comment by cecheta** [comment]
> This is part of the effort to keep a single front end for multiple backend:
> 
> * Standard GPT
> * Chat with your own data
> * Custom Backend
>   I won't remove it as it's used by customers and removing it doesn't add any value.

Thanks for the input @ruoccofabrizio, 

I would have thought that if users were looking for a standard GPT they would use https://github.com/microsoft/sample-app-aoai-chatGPT, however if customers are currently using it then I will add it back

**Comment by cecheta** [comment]
"Without data" re-introduced

**Review by ross-p-smith — APPROVED** [review]

**Pull request merged**
