### PR TITLE
Always destroy

### PR DESCRIPTION
**Pull request by ross-p-smith**
## Purpose
We should always destroy what we just built

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## How to Test
Does it destroy the environment

image

### CODE REVIEW

**Comment by superhindupur** [comment]
I was doing the same thing today after the discussion this morning. But I see you’ve created the pr already. I was trialing this along with the ui tests on my branch today.

**Comment by ross-p-smith** [comment]
> I was doing the same thing today after the discussion this morning. But I see you’ve created the pr already. I was trialing this along with the ui tests on my branch today.

Oh really sorry! That's 2 people I've done that too today! :-( Sorry

**Review by cecheta — APPROVED** [review]

**Comment by superhindupur** [comment]
Can you add a link to the passing build from before you merged this, so we have a record of testing this before we merged it?

**Comment by ross-p-smith** [comment]
https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/actions/runs/8457495014/job/23169582713

**Pull request merged**
