### PR TITLE
Update Docker build workflows to use the official action

### PR DESCRIPTION
**Pull request by superhindupur**
## Purpose
This PR replaces the custom script inside all three docker github workflows with the docker/build-push-action. This makes the github action configuration more readable and maintainable.

Required by #605.

## Does this introduce a breaking change?

```
[ ] Yes
[x ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[x ] Other... Updates the CI/CD configuration.
```

## How to Test
Here's a passing build from my changes on my feature branch: https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/actions/runs/8741684840

### CODE REVIEW

**Comment by ross-p-smith** [comment]
Great work! Is this just an initial replacement and there will be a further PR to change to only push when on main?
- build on all branches
- only push when on main

Maybe make it clear in the tasks section that this is just the part 1 if that is your intention

**Comment by superhindupur** [comment]
That's correct. This just addresses part of the issue - just to replace the existing scripts with the official GitHub action. 

I will link this PR on the relevant task on the issue to make it clear, thanks.

**Review by adamdougal — APPROVED** [review]
LGTM!

I'm wondering if there's a way for us to reuse a single workflow and parameterise it, but we can look at that later.

**Comment by superhindupur** [comment]
> LGTM!
> 
> I'm wondering if there's a way for us to reuse a single workflow and parameterise it, but we can look at that later.

Good idea, will keep that in mind as I make more change to this workflow under #605

**Pull request merged**
