### PR TITLE
Remove venv from codebase

### PR DESCRIPTION
**Pull request by cecheta**
## Purpose

* Fixes issue with debugging Azure Functions in VS Code, by removing all references to venvs

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
* Rebuild devcontainer in VS Code
* Create `code/backend/batch/local.settings.json` with storage connection string value for `AzureWebJobsStorage`
* Run "Attach to Python Functions" within "Run and Debug"

## What to Check
* Functions start locally

image

### CODE REVIEW

**Review by komalg1 — DISMISSED** [review]
LGTM!

**Comment by cecheta** [comment]
> My question here is "why" does Functions need a venv? Will Functions work if we remove that setting?

The description for `azureFunctions.pythonVenv` says:

> The name of the Python virtual environment used for your project. A virtual environment is required to debug and deploy Python functions.

I could try removing all references to `.venv` and see if that works, what do you think?

**Comment by ross-p-smith** [comment]
I know it's a pain - but are you able to try? We are not using a venv for the other python parts of this project and I'm inclined to not introduce it if we can help it

**Comment by cecheta** [comment]
> I know it's a pain - but are you able to try? We are not using a venv for the other python parts of this project and I'm inclined to not introduce it if we can help it

Tested locally without a venv in a new container and seemed to work fine

**Review by ross-p-smith — APPROVED** [review]
Many thanks!

**Pull request merged**
