### PR TITLE
style: Create a pre-commit hook for checking snake casing of files.

### PR DESCRIPTION
**Pull request by gaurarpit**
## Purpose

* Create a pre-commit hook for checking snake casing of files

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## How to Test
* Tested locally by manually changing file names and casing.

### CODE REVIEW

**Comment by ross-p-smith** [comment]
I thought we spoke about this in Sprint Planning that this has no value.

**Comment by gaurarpit** [comment]
> I thought we spoke about this in Sprint Planning that this has no value.

it was already done.

**Comment by adamdougal** [comment]
I think it's probably worth leaving this out for now, maybe we can add it in if we start active work on this project again.

**Comment by gaurarpit** [comment]
> I think it's probably worth leaving this out for now, maybe we can add it in if we start active work on this project again.

Sure, I agree with you. I'll abandon this PR for now.

**Pull request closed without merging**
