### PR TITLE
Move python tests to root

### LINKED ISSUE #200: Unit tests should be run on a Pull Request
We are starting to add some tests (e.g #193) - let's

- [ ] Pull the tests into a better directory location
- [ ] Split the tests into integration and units tests
- [ ] Run them as part of a build

### PR DESCRIPTION
**Pull request by ross-p-smith**
## Purpose
Pull the Unit Tests into a folder from the root so that we don't deploy them

Fixes #200 

Most tests are disabled as they require Azure Services. We can enable them once we have CD. This is an interim PR so that we can ask contributors to add tests and know that they will be run.

## Does this introduce a breaking change?
```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
Unit Tests should run from a PR with this change 🤞

image

### CODE REVIEW

**Comment by cecheta** [comment]
The custom marks aren't working, I think you need to move `pytest.ini` to the root of the repo

image

**Comment by cecheta** [comment]
The custom marks aren't working, I think you need to move `pytest.ini` to the root of the repo

image

**Comment by ross-p-smith** [comment]
> The custom marks aren't working, I think you need to move `pytest.ini` to the root of the repo
> 

Thanks! Great spot - looks better now @cecheta 
image

**Review by cecheta — APPROVED** [review]
Nice :)

**Pull request merged**
